version: "3.9"
services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root1234}
    ports:
      - "3306:3306"
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    networks:
      - host
